version: "3.9"

services:
  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
      PGADMIN_CONFIG_SERVER_MODE: "True"
      TZ: ${TZ}

    secrets:
      - pgadmin_password

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    networks:
      - edge

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=${EDGE_NETWORK}

        - traefik.http.routers.pgadmin.rule=Host(`${DNS_PREFIX}.pgadmin.${BASE_DOMAIN}`)
        - traefik.http.routers.pgadmin.entrypoints=websecure
        - traefik.http.routers.pgadmin.tls=true
        - traefik.http.routers.pgadmin.tls.certresolver=letsencryptresolver

        - traefik.http.services.pgadmin.loadbalancer.server.port=80

networks:
  edge:
    external: true
    name: "${EDGE_NETWORK}"

secrets:
  pgadmin_password:
    external: true
    name: ${STACK_PREFIX}_pgadmin_password

volumes:
  pgadmin_data:
    external: true
    name: ${STACK_PREFIX}_pgadmin_data
