version: "3.7"

services:
  pgadmin:
    image: dpage/pgadmin4:8
    networks:
      - edge
      - data
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/pgadmin_password

      - PGADMIN_CONFIG_PROXY_X_FOR_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PROTO_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_HOST_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PORT_COUNT=1
      - PGADMIN_CONFIG_SESSION_COOKIE_SECURE=True
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
      - PGADMIN_CONFIG_WTF_CSRF_SSL_STRICT=False

    secrets:
      - pgadmin_password

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.pgadmin.rule=Host(`${DOMAIN_PGADMIN}`)
        - traefik.http.routers.pgadmin.entrypoints=websecure
        - traefik.http.routers.pgadmin.tls.certresolver=letsencryptresolver
        - traefik.http.services.pgadmin.loadbalancer.server.port=80
        - traefik.http.middlewares.pgadmin-sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.pgadmin.middlewares=pgadmin-sslheader@docker

secrets:
  pgadmin_password:
    external: true
    name: "${TENANT}_${ENV}_pgadmin_password"

volumes:
  pgadmin_data:
    external: true
    name: "${TENANT}_${ENV}_pgadmin_data"

networks:
  edge:
    external: true
    name: "${EDGE_NETWORK}"
  data:
    external: true
    name: "${DATA_NETWORK}"