version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:2.20.3
    command: ["--http-enabled"]
    volumes:
      - ${TENANT}_${ENV}_portainer_data:/data
    networks:
      - net_edge
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=net_edge

        - traefik.http.routers.portainer.rule=Host(`${TENANT}.portainer.${BASE_DOMAIN}`)
        - traefik.http.routers.portainer.entrypoints=websecure
        - traefik.http.routers.portainer.tls=true
        - traefik.http.routers.portainer.tls.certresolver=letsencryptresolver

        - traefik.http.services.portainer.loadbalancer.server.port=9000

  portainer_agent:
    image: portainer/agent:2.20.3
    networks:
      - net_edge
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

volumes:
  ${TENANT}_${ENV}_portainer_data:
    external: true

networks:
  net_edge:
    external: true
    name: net_edge
