version: "3.7"

services:
  portainer:
    image: portainer/portainer-ce:2.20.3
    command: ["--http-enabled"]
    volumes:
      - portainer_data:/data
    networks:
      - edge
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true

        # ✅ padrão: fixa a network que o Traefik usa
        - traefik.docker.network=${EDGE_NETWORK}

        # ✅ padrão: DNS derivado no YAML
        - traefik.http.routers.portainer.rule=Host(`${DNS_PREFIX}.portainer.${BASE_DOMAIN}`)
        - traefik.http.routers.portainer.entrypoints=websecure
        - traefik.http.routers.portainer.tls=true
        - traefik.http.routers.portainer.tls.certresolver=letsencryptresolver

        - traefik.http.services.portainer.loadbalancer.server.port=9000

  portainer_agent:
    image: portainer/agent:2.20.3
    networks:
      - edge
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

volumes:
  portainer_data:
    external: true
    name: "${STACK_PREFIX}_portainer_data"

networks:
  edge:
    external: true
    name: "${EDGE_NETWORK}"
