version: "3.7"

services:
  redis:
    image: redis:7-alpine
    command:
      [
        "redis-server",
        "--appendonly", "yes",
        "--port", "6379",
        "--maxmemory", "768mb",
        "--maxmemory-policy", "allkeys-lru",
        "--save", "",
        "--protected-mode", "yes"
      ]
    volumes:
      - redis_data:/data
    networks:
      - data
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
    stop_grace_period: 30s
    ulimits:
      nofile:
        soft: 10032
        hard: 10032
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  redis_data:
    external: true
    name: "${TENANT}_${ENV}_redis_data"

networks:
  data:
    external: true
    name: "${DATA_NETWORK}"
