version: "3.7"

x-n8n-env: &n8n_env
  # Banco
  DB_TYPE: postgresdb
  DB_POSTGRESDB_HOST: postgres
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: n8n_queue
  DB_POSTGRESDB_USER: postgres
  DB_POSTGRESDB_PASSWORD_FILE: /run/secrets/postgres_password

  # URLs / Host
  N8N_HOST: ${DNS_PREFIX}.n8n.${BASE_DOMAIN}
  N8N_PROTOCOL: https
  N8N_EDITOR_BASE_URL: https://${DNS_PREFIX}.n8n.${BASE_DOMAIN}
  WEBHOOK_URL: https://${DNS_PREFIX}.n8n.${BASE_DOMAIN}

  # Execução em fila
  EXECUTIONS_MODE: queue
  QUEUE_BULL_REDIS_HOST: redis
  QUEUE_BULL_REDIS_PORT: "6379"
  QUEUE_BULL_REDIS_DB: "2"
  QUEUE_BULL_REDIS_PASSWORD_FILE: /run/secrets/redis_password

  # Geral
  NODE_ENV: production
  GENERIC_TIMEZONE: ${TZ}
  TZ: ${TZ}

  EXECUTIONS_DATA_PRUNE: "true"
  EXECUTIONS_DATA_MAX_AGE: "336"

  N8N_LOG_LEVEL: info
  N8N_DIAGNOSTICS_ENABLED: "false"
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"

services:
  n8n_editor:
    image: n8nio/n8n:1.90.2
    networks:
      - edge
      - data
    environment:
      <<: *n8n_env
    secrets:
      - postgres_password
      - redis_password
      - n8n_encryption_key
    volumes:
      - n8n_data:/home/node/.n8n
      - n8n_files:/files
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=${EDGE_NETWORK}
        - traefik.http.routers.n8n_editor.rule=Host(`${DNS_PREFIX}.n8n.${BASE_DOMAIN}`)
        - traefik.http.routers.n8n_editor.entrypoints=websecure
        - traefik.http.routers.n8n_editor.tls.certresolver=letsencryptresolver
        - traefik.http.services.n8n_editor.loadbalancer.server.port=5678

  n8n_webhook:
    image: n8nio/n8n:1.90.2
    networks:
      - edge
      - data
    environment:
      <<: *n8n_env
    secrets:
      - postgres_password
      - redis_password
      - n8n_encryption_key
    volumes:
      - n8n_data:/home/node/.n8n
      - n8n_files:/files
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=${EDGE_NETWORK}
        - traefik.http.routers.n8n_webhook.rule=Host(`${DNS_PREFIX}.n8n.${BASE_DOMAIN}`) && (PathPrefix(`/webhook`) || PathPrefix(`/webhook-test`))
        - traefik.http.routers.n8n_webhook.entrypoints=websecure
        - traefik.http.routers.n8n_webhook.priority=10
        - traefik.http.routers.n8n_webhook.tls.certresolver=letsencryptresolver
        - traefik.http.services.n8n_webhook.loadbalancer.server.port=5678

  n8n_worker:
    image: n8nio/n8n:1.90.2
    networks:
      - data
    environment:
      <<: *n8n_env
    secrets:
      - postgres_password
      - redis_password
      - n8n_encryption_key
    volumes:
      - n8n_data:/home/node/.n8n
      - n8n_files:/files
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

secrets:
  postgres_password:
    external: true
    name: ${STACK_PREFIX}_postgres_password

  redis_password:
    external: true
    name: ${STACK_PREFIX}_redis_password

  n8n_encryption_key:
    external: true
    name: ${STACK_PREFIX}_n8n_encryption_key

volumes:
  n8n_data:
    external: true
    name: ${STACK_PREFIX}_n8n_data

  n8n_files:
    external: true
    name: ${STACK_PREFIX}_n8n_files

networks:
  edge:
    external: true
    name: ${EDGE_NETWORK}

  data:
    external: true
    name: ${DATA_NETWORK}
