version: "3.7"

services:
  evolution_test:
    image: evoapicloud/evolution-api:v2.3.7
    command: ["node", "./dist/src/main.js"]
    networks:
      - data
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store

    environment:
      TZ: America/Sao_Paulo
      DOCKER_ENV: "true"
      SERVER_URL: "https://thermas.evo.pulse4mind.com"

      AUTHENTICATION_TYPE: "apikey"
      AUTHENTICATION_API_KEY: "TESTE_TEMPORARIO"

      DATABASE_ENABLED: "true"
      DATABASE_PROVIDER: "postgresql"

      # ⚠️ TESTE HARD CODED
      DATABASE_URL: "postgresql://postgres:AdminAdmin@postgres:5432/evolution_db?schema=evolution_api"
      DATABASE_CONNECTION_URI: "postgresql://postgres:AdminAdmin@postgres:5432/evolution_db?schema=evolution_api"

      CACHE_REDIS_ENABLED: "false"
      CACHE_LOCAL_ENABLED: "true"

      LOG_LEVEL: "ERROR,WARN,INFO,DEBUG"

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  evolution_instances:
    external: true
    name: "${TENANT}_${ENV}_evolution_instances"
  evolution_store:
    external: true
    name: "${TENANT}_${ENV}_evolution_store"

networks:
  data:
    external: true
    name: "${DATA_NETWORK}"
