version: "3.7"

x-evolution-env: &evolution_env
  TZ: ${TZ}
  DOCKER_ENV: "true"
  SERVER_URL: "https://${DNS_PREFIX}.evo.${BASE_DOMAIN}"

  AUTHENTICATION_TYPE: "apikey"

  DATABASE_ENABLED: "true"
  DATABASE_PROVIDER: "postgresql"

  CACHE_REDIS_ENABLED: "true"
  CACHE_LOCAL_ENABLED: "false"
  CACHE_REDIS_PREFIX_KEY: "${EVO_CACHE_PREFIX}"
  EVO_CACHE_REDIS_DB: "${EVO_CACHE_REDIS_DB}"

  LOG_LEVEL: "${EVO_LOG_LEVEL}"

services:
  evolution_api:
    image: evoapicloud/evolution-api:v2.3.7
    entrypoint: ["/bin/sh", "-lc"]
    command:
      - >-
        set -eu;
        echo "== Evolution bootstrap starting ==";
        test -f /run/secrets/postgres_password || { echo "ERROR missing postgres_password"; ls -lah /run/secrets || true; sleep 600; exit 1; };
        test -f /run/secrets/redis_password || { echo "ERROR missing redis_password"; ls -lah /run/secrets || true; sleep 600; exit 1; };
        test -f /run/secrets/evolution_api_key || { echo "ERROR missing evolution_api_key"; ls -lah /run/secrets || true; sleep 600; exit 1; };

        AUTHENTICATION_API_KEY="$$(cat /run/secrets/evolution_api_key | tr -d '\r\n')";

        POSTGRES_PASSWORD_ENC="$$(node -e "process.stdout.write(encodeURIComponent(require('fs').readFileSync('/run/secrets/postgres_password','utf8').trim()))")";
        REDIS_PASSWORD_ENC="$$(node -e "process.stdout.write(encodeURIComponent(require('fs').readFileSync('/run/secrets/redis_password','utf8').trim()))")";

        PG_HOST="$${POSTGRES_HOST:-postgres}";
        PG_PORT="$${POSTGRES_PORT:-5432}";
        RD_HOST="$${REDIS_HOST:-redis}";
        RD_PORT="$${REDIS_PORT:-6379}";

        DB_NAME="$${EVO_DB_NAME:-evolution_db}";
        DB_SCHEMA="$${EVO_DB_SCHEMA:-evolution_api}";

        DB_URI="postgresql://postgres:$${POSTGRES_PASSWORD_ENC}@$${PG_HOST}:$${PG_PORT}/$${DB_NAME}?schema=$${DB_SCHEMA}";
        REDIS_URI="redis://:$${REDIS_PASSWORD_ENC}@$${RD_HOST}:$${RD_PORT}/$${EVO_CACHE_REDIS_DB}";

        export AUTHENTICATION_API_KEY="$$AUTHENTICATION_API_KEY";
        export DATABASE_CONNECTION_URI="$$DB_URI";
        export DATABASE_URL="$$DB_URI";
        export CACHE_REDIS_URI="$$REDIS_URI";

        echo "== Running migrations (db:deploy) ==";
        npm run db:deploy || { echo "ERROR: db:deploy failed"; sleep 600; exit 1; };

        echo "== Starting Evolution ==";
        exec npm run start:prod

    environment:
      <<: *evolution_env

    networks:
      - edge
      - data

    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store

    secrets:
      - source: evolution_api_key
        target: evolution_api_key
      - source: postgres_password
        target: postgres_password
      - source: redis_password
        target: redis_password

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
      labels:
        - traefik.enable=true
        - traefik.docker.network=${EDGE_NETWORK}
        - traefik.http.routers.evolution.rule=Host(`${DNS_PREFIX}.evo.${BASE_DOMAIN}`)
        - traefik.http.routers.evolution.entrypoints=websecure
        - traefik.http.routers.evolution.tls.certresolver=letsencryptresolver
        - traefik.http.services.evolution.loadbalancer.server.port=8080

secrets:
  evolution_api_key:
    external: true
    name: "${STACK_PREFIX}_evolution_api_key"
  postgres_password:
    external: true
    name: "${STACK_PREFIX}_postgres_password"
  redis_password:
    external: true
    name: "${STACK_PREFIX}_redis_password"

volumes:
  evolution_instances:
    external: true
    name: "${STACK_PREFIX}_evolution_instances"
  evolution_store:
    external: true
    name: "${STACK_PREFIX}_evolution_store"

networks:
  edge:
    external: true
    name: "${EDGE_NETWORK}"
  data:
    external: true
    name: "${DATA_NETWORK}"
